/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proj;

import java.awt.Color;
import static java.awt.Component.CENTER_ALIGNMENT;
import java.awt.Dimension;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;
import static proj.Connections.con;
import ttable.modeel;
import ttable.query11;
import ttable.t1;

/**
 *
 * @author emada
 */
public class accounts extends javax.swing.JPanel {

   private static int headeer=40;
    public accounts() {
          try {
            UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(panel2.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(panel2.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(panel2.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(panel2.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //..................
        initComponents();
        panelbody.removeAll();   // Here I am hide any panel just show panelbody
        table1();
        
        jScrollPane1.getVerticalScrollBar().setUI(new MyScrollBarUI());
       jScrollPane1.getHorizontalScrollBar().setUI(new MyScrollBarUI());
       jScrollPane2.getVerticalScrollBar().setUI(new MyScrollBarUI());
       jScrollPane2.getHorizontalScrollBar().setUI(new MyScrollBarUI());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        panelbody = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        arbahi = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jdeon = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton11 = new javax.swing.JButton();

        setBackground(new java.awt.Color(44, 62, 80));

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("الحسابات");

        jButton4.setBackground(new java.awt.Color(0, 153, 153));
        jButton4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(204, 204, 204));
        jButton4.setText("الديون");
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setOpaque(true);
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton4MouseExited(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 153, 153));
        jButton5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(204, 204, 204));
        jButton5.setText("الارباح");
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.setOpaque(true);
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton5MouseExited(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(0, 153, 153));
        jButton9.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(204, 204, 204));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/report.png"))); // NOI18N
        jButton9.setText("جرد المبيعات");
        jButton9.setBorder(null);
        jButton9.setContentAreaFilled(false);
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.setOpaque(true);
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton9MouseExited(evt);
            }
        });
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        panelbody.setBackground(new java.awt.Color(44, 62, 80));
        panelbody.setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("صافي الارباح");

        arbahi.setBackground(new java.awt.Color(51, 51, 51));
        arbahi.setFont(new java.awt.Font("Arial", 0, 28)); // NOI18N
        arbahi.setForeground(new java.awt.Color(75, 217, 65));
        arbahi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        arbahi.setText("6.575.400");
        arbahi.setOpaque(true);

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("د.ع");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(287, 287, 287)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(arbahi, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(193, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(arbahi, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(278, Short.MAX_VALUE))
        );

        panelbody.add(jPanel1, "card2");

        jPanel2.setBackground(new java.awt.Color(44, 62, 80));

        jTable1.setBackground(new java.awt.Color(204, 204, 204));
        jTable1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jdeon.setBackground(new java.awt.Color(0, 0, 0));
        jdeon.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jdeon.setForeground(new java.awt.Color(255, 51, 51));
        jdeon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jdeon.setText("0");
        jdeon.setOpaque(true);

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("مجموع الديون");

        jButton10.setBackground(new java.awt.Color(255, 0, 0));
        jButton10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Delete-icon.png"))); // NOI18N
        jButton10.setText("حذف ديون");
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton10)
                .addGap(77, 77, 77))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 988, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(jdeon, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jdeon, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 94, Short.MAX_VALUE))
        );

        panelbody.add(jPanel2, "card3");

        jPanel3.setBackground(new java.awt.Color(44, 62, 80));

        jTable2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton11.setBackground(new java.awt.Color(255, 0, 0));
        jButton11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Delete-icon.png"))); // NOI18N
        jButton11.setText("حذف مبيعات");
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1031, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton11)
                .addGap(42, 42, 42))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        panelbody.add(jPanel3, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(466, 466, 466)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(235, 235, 235)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 231, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelbody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(479, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 160, Short.MAX_VALUE)
                    .addComponent(panelbody, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseEntered

    private void jButton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseExited

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        panelbody.removeAll();
      panelbody.repaint();
      panelbody.revalidate();
      panelbody.add(jPanel2);
      panelbody.repaint();
      panelbody.revalidate();
      
      
    Statement stmt = null ;
        PreparedStatement pst;
        ResultSet rs;
       
try{
   con=Connections.getConnection();
    String sql="SELECT (SELECT SUM (priceremain)FROM deon) AS priceiqq ";
   stmt=con.createStatement();
    rs=stmt.executeQuery(sql);
    
    
    
    while(rs.next()){
        
      
        
        jdeon.setText(rs.getString("priceiqq")+"   د.ع");
     
      
        
    }
    
    
    
    
    
    
    
    
}
catch(Exception e){
    JOptionPane.showMessageDialog(null, e);
    
}
      
      
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5MouseEntered

    private void jButton5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5MouseExited

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
      panelbody.removeAll();
      panelbody.repaint();
      panelbody.revalidate();
      panelbody.add(jPanel1);
      panelbody.repaint();
      panelbody.revalidate();
      
      
      
     
  
   
 
    Statement stmt = null ;
        PreparedStatement pst;
        ResultSet rs;
       
try{
   con=Connections.getConnection();
    String sql="SELECT (SELECT SUM (pricepaid)FROM deon)+(SELECT SUM (totalprice)FROM Table_2)-(SELECT SUM (totalprice)FROM DITEM) AS priceiqq ";
   stmt=con.createStatement();
    rs=stmt.executeQuery(sql);
    
    
    
    while(rs.next()){
        
      
        
        arbahi.setText(rs.getString("priceiqq"));
      
    }
  String aa=arbahi.getText();
  int a=Integer.parseInt(aa);
   if(a < 0){
       
       arbahi.setForeground(Color.red);
   }
   if(a > 0){
       
       arbahi.setForeground(Color.GREEN);
   } 
    
   if(a == 0){
       
       arbahi.setForeground(Color.YELLOW);
   }  
    
}
catch(Exception e){
   JOptionPane.showMessageDialog(null, "لاتوجد مبيعات");
           
    
}
    
    
    
    

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        jButton9.setBackground(new Color(49,60,60));
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseEntered
      
    }//GEN-LAST:event_jButton9MouseEntered

    private void jButton9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9MouseExited

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        panelbody.removeAll();  /* Add panel1 one */
        panelbody.repaint();
        panelbody.revalidate();
        panelbody.add(jPanel3);
        panelbody.repaint();
        panelbody.revalidate();
        table1();
        table2();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        try{
           con=Connections.getConnection();

            int aa=jTable2.getSelectedRow();
            String aaa=(jTable2.getModel().getValueAt(aa,0).toString());
            String sql="DELETE  FROM Table_2 WHERE id="+aaa;
            PreparedStatement pst=con.prepareStatement(sql);

            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "تم الحذف");
            table2();
        }
        catch(Exception e){
            System.out.print(e);

        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed

        try{
           con=Connections.getConnection();

            int aa=jTable1.getSelectedRow();
            String aaa=(jTable1.getModel().getValueAt(aa,0).toString());
            String sql="DELETE  FROM deon WHERE id="+aaa;

            PreparedStatement pst=con.prepareStatement(sql);

            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "تم الحذف");
            table1();
        }
        catch(Exception e){
            System.out.print(e);

        }

    }//GEN-LAST:event_jButton10ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arbahi;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel jdeon;
    private javax.swing.JPanel panelbody;
    // End of variables declaration//GEN-END:variables


public void table1(){
    
  
 query11 mq = new query11();
        ArrayList<t1> list = mq.wwww();
        String[] columnName = {"التسلسل","الاسم","اسم المادة","الكمية","السعر","المبلغ المدفوع","المبلغ المتبقي","المجموع الكلي","التاريخ"};
        Object[][] rows = new Object[list.size()][9];
        for(int i = 0; i < list.size(); i++){
            
            rows[i][0]=list.get(i).getIID();
            rows[i][1]=list.get(i).getNname();
            rows[i][2]=list.get(i).getName();
            rows[i][3]=list.get(i).getkmeaa();
            rows[i][4]=list.get(i).getpriceiq()+" د.ع";
            rows[i][5]=list.get(i).getpricedolar()+" د.ع";
            rows[i][6]=list.get(i).getPriceremain()+" د.ع";
            rows[i][7]=list.get(i).getTotalprice()+" د.ع";
            rows[i][8]=list.get(i).getDate();
           
         
           
        }
        
        modeel model = new modeel(rows, columnName);
        jTable1.setModel(model);
        jTable1.setRowHeight(40);
       jTable1.getTableHeader().setReorderingAllowed(false);
       
   JTableHeader theader = jTable1.getTableHeader();
   theader.setBackground(Color.BLACK);
     theader.setPreferredSize(new Dimension(100, headeer));
    
       theader.setForeground(Color.WHITE);
       
          Font f = new Font("Arial", Font.BOLD, 20);
           theader.setFont(f);
            ((DefaultTableCellRenderer)theader.getDefaultRenderer())
             .setHorizontalAlignment(JLabel.CENTER);
         /*.....>.......................................................................*/
             DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
          rightRenderer.setHorizontalAlignment((int) CENTER_ALIGNMENT);
       TableModel tableModel = jTable1.getModel();
      for (int columnIndex = 0; columnIndex < tableModel.getColumnCount(); columnIndex++)
   {
    jTable1.getColumnModel().getColumn(columnIndex).setCellRenderer(rightRenderer);
 }
    
}
public void table2(){
    
    query1 mq = new query1();
        ArrayList<product1> list = mq.www();
        String[] columnName = {"التسلسل","المادة","النوعية","الكمية","المبلغ","المبلغ الكلي"};
        Object[][] rows = new Object[list.size()][7];
        for(int i = 0; i < list.size(); i++){
            
            rows[i][0]=list.get(i).getId();
            rows[i][1]=list.get(i).getName();
            rows[i][2]=list.get(i).getType();
            rows[i][3]=list.get(i).getkmeaa();
            rows[i][4]=list.get(i).getPrice();
            rows[i][5]=list.get(i).getTotal();
         
           
        }
        
        themodel model = new themodel(rows, columnName);
        jTable2.setModel(model);
        jTable2.setRowHeight(40);
       jTable2.getTableHeader().setReorderingAllowed(false);
       
   JTableHeader theader = jTable2.getTableHeader();
   theader.setBackground(Color.ORANGE);
     theader.setPreferredSize(new Dimension(100, headeer));
    
       theader.setForeground(Color.WHITE);
       
          Font f = new Font("Arial", Font.BOLD, 20);
           theader.setFont(f);
            ((DefaultTableCellRenderer)theader.getDefaultRenderer())
             .setHorizontalAlignment(JLabel.CENTER);
         /*.....>.......................................................................*/
             DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
          rightRenderer.setHorizontalAlignment((int) CENTER_ALIGNMENT);
       TableModel tableModel = jTable2.getModel();
      for (int columnIndex = 0; columnIndex < tableModel.getColumnCount(); columnIndex++)
   {
    jTable2.getColumnModel().getColumn(columnIndex).setCellRenderer(rightRenderer);
 }  
    
    
    
    
}



public void table3(){
    
  
 query11 mq = new query11();
        ArrayList<t1> list = mq.wwww();
        String[] columnName = {"التسلسل","المادة","النوعية","الكمية","المبلغ","المبلغ الكلي"};
        Object[][] rows = new Object[list.size()][9];
        for(int i = 0; i < list.size(); i++){
            
            rows[i][0]=list.get(i).getIID();
            rows[i][1]=list.get(i).getNname();
            rows[i][2]=list.get(i).getName();
            rows[i][3]=list.get(i).getkmeaa();
            rows[i][4]=list.get(i).getpriceiq()+" د.ع";
            rows[i][5]=list.get(i).getpricedolar()+" د.ع";
            rows[i][6]=list.get(i).getPriceremain()+" د.ع";
            rows[i][7]=list.get(i).getTotalprice()+" د.ع";
            rows[i][8]=list.get(i).getDate();
           
         
           
        }
        
        modeel model = new modeel(rows, columnName);
        jTable1.setModel(model);
        jTable1.setRowHeight(40);
       jTable1.getTableHeader().setReorderingAllowed(false);
       
   JTableHeader theader = jTable1.getTableHeader();
   theader.setBackground(Color.BLACK);
     theader.setPreferredSize(new Dimension(100, headeer));
    
       theader.setForeground(Color.WHITE);
       
          Font f = new Font("Arial", Font.BOLD, 20);
           theader.setFont(f);
            ((DefaultTableCellRenderer)theader.getDefaultRenderer())
             .setHorizontalAlignment(JLabel.CENTER);
         /*.....>.......................................................................*/
             DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
          rightRenderer.setHorizontalAlignment((int) CENTER_ALIGNMENT);
       TableModel tableModel = jTable1.getModel();
      for (int columnIndex = 0; columnIndex < tableModel.getColumnCount(); columnIndex++)
   {
    jTable1.getColumnModel().getColumn(columnIndex).setCellRenderer(rightRenderer);
 }
    
}


}
