/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proj;

import java.awt.Color;
import static java.awt.Component.CENTER_ALIGNMENT;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.PopupMenu;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;

import proj.tablee.query12;
import proj.tablee.t12;
import ttable.modeel;

/**
 *
 * @author emada
 */
public class jm extends javax.swing.JPanel {

      private static int headeer=40;
      
      
    public jm() {
        
        
            
         try {
            UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(panel2.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(panel2.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(panel2.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(panel2.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        
          
        
        //............................
         query11 mq = new query11();
        ArrayList<product11> list = mq.www();
        String[] columnName = {"التسلسل","اسم المادة","النوعية","الكمية","السعر","سعر البيع","المجموع الكلي"};
        Object[][] rows = new Object[list.size()][8];
        for(int i = 0; i < list.size(); i++){
            
             rows[i][0]=list.get(i).getID();
           
             rows[i][1]=list.get(i).getName();
             rows[i][2]=list.get(i).gettype();
             rows[i][3]=list.get(i).getkmeaa();
             rows[i][4]=list.get(i).getprice()+" د.ع";
             rows[i][5]=list.get(i).getpriceremain()+" د.ع";
             rows[i][6]=list.get(i).gettotal()+" د.ع";
           
           
          
           
        }
        
        themodel model = new themodel(rows, columnName);
        jTable1.setModel(model);
        jTable1.setRowHeight(40);
        
   JTableHeader theader = jTable1.getTableHeader();
   theader.setBackground(Color.ORANGE);
     theader.setPreferredSize(new Dimension(100, headeer));
     
       theader.setForeground(Color.black);
       
          Font f = new Font("Arial", Font.BOLD, 20);
           theader.setFont(f);
            ((DefaultTableCellRenderer)theader.getDefaultRenderer())
             .setHorizontalAlignment(JLabel.CENTER);
         /*.....>.......................................................................*/
             DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
          rightRenderer.setHorizontalAlignment((int) CENTER_ALIGNMENT);
       TableModel tableModel = jTable1.getModel();
      for (int columnIndex = 0; columnIndex < tableModel.getColumnCount(); columnIndex++)
   {
    jTable1.getColumnModel().getColumn(columnIndex).setCellRenderer(rightRenderer);
 }
      //.............................
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setBackground(new java.awt.Color(44, 62, 80));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton3.setBackground(new java.awt.Color(0, 153, 153));
        jButton3.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add-icon.png"))); // NOI18N
        jButton3.setText("ادخال الى المخزن");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 102, 102));
        jButton4.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Delete-icon.png"))); // NOI18N
        jButton4.setText("تراجع عن الشراء");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(58, 58, 58))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(519, 519, 519)
                .addComponent(jButton3)
                .addContainerGap(400, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
   
        try{
            String url="jdbc:sqlserver://localhost:1433;databaseName=mbeaat1;user=adminn;password=1991";
            Connection con=DriverManager.getConnection(url);
            
            int  aa=jTable1.getSelectedRow();
        
          
           String aaa=(jTable1.getModel().getValueAt(aa,0).toString());
          
            String ssql="DELETE [dbo].[DITEM]\n" +
"      WHERE id=" +aaa;
            
            
             PreparedStatement psst=con.prepareStatement(ssql);
          
         psst.executeUpdate();
           int  aaaa=jTable1.getSelectedRow();
        
          
           String aaaaa=(jTable1.getModel().getValueAt(aaaa,0).toString());
   String sql="DELETE [dbo].[ITEM]\n" +
"      WHERE iid=" +aaa;
              
             PreparedStatement pst=con.prepareStatement(sql);
          
         pst.executeUpdate();

            
            
            JOptionPane.showMessageDialog(null, "تم الحذف");
            
          
             table1();
        }
        catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
            
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    try{
            String url="jdbc:sqlserver://localhost:1433;databaseName=mbeaat1;user=adminn;password=1991";
            Connection con=DriverManager.getConnection(url);
            
            int  aa=jTable1.getSelectedRow();
        
          
           String aaa=(jTable1.getModel().getValueAt(aa,0).toString());
           String bbb=(jTable1.getModel().getValueAt(aa,1).toString());
           String ccc=(jTable1.getModel().getValueAt(aa,2).toString());
           String ddd=(jTable1.getModel().getValueAt(aa,3).toString());
           String ssql="INSERT INTO [dbo].[makhzn] (namee,typeee,kmeaa) VALUES(?,?,?)";
            
            
             PreparedStatement pst=con.prepareStatement(ssql);
             
             pst.setString(1, bbb); 
             pst.setString(2, ccc); 
             pst.setString(3, ddd);
             
             
             pst.executeUpdate();
   
              
             

            
            
            JOptionPane.showMessageDialog(null, "تم ترحيل المواد الى المخزن");
            
          
            
        }
        catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
            
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

public void table1(){
    
    
    
         query11 mq = new query11();
        ArrayList<product11> list = mq.www();
        String[] columnName = {"التسلسل","اسم المادة","النوعية","الكمية","السعر","الباقي","المجموع الكلي"};
        Object[][] rows = new Object[list.size()][8];
        for(int i = 0; i < list.size(); i++){
            rows[i][0]=list.get(i).getID();
            
             rows[i][1]=list.get(i).getName();
             rows[i][2]=list.get(i).gettype();
             rows[i][3]=list.get(i).getkmeaa();
             rows[i][4]=list.get(i).getprice()+" د.ع";
             rows[i][5]=list.get(i).getpriceremain()+" د.ع";
             rows[i][6]=list.get(i).gettotal()+" د.ع";
           
           
          
           
        }
        
        themodel model = new themodel(rows, columnName);
        jTable1.setModel(model);
        jTable1.setRowHeight(40);
        
   JTableHeader theader = jTable1.getTableHeader();
   theader.setBackground(Color.ORANGE);
     theader.setPreferredSize(new Dimension(100, headeer));
     
       theader.setForeground(Color.black);
       
          Font f = new Font("Arial", Font.BOLD, 20);
           theader.setFont(f);
            ((DefaultTableCellRenderer)theader.getDefaultRenderer())
             .setHorizontalAlignment(JLabel.CENTER);
         /*.....>.......................................................................*/
             DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
          rightRenderer.setHorizontalAlignment((int) CENTER_ALIGNMENT);
       TableModel tableModel = jTable1.getModel();
      for (int columnIndex = 0; columnIndex < tableModel.getColumnCount(); columnIndex++)
   {
    jTable1.getColumnModel().getColumn(columnIndex).setCellRenderer(rightRenderer);
 } 
    
    
}


    
    
    
    



}
