/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proj;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;
import static proj.Connections.con;



/**
 *
 * @author emada
 */
public class paneladdm11 extends javax.swing.JPanel {

    private static int headeer=40;
    /**
     * Creates new form paneladdm
     */
    public paneladdm11() {
          try {
            UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(panel2.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(panel2.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(panel2.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(panel2.class.getName()).log(Level.SEVERE, null, ex);
        }
        /*................*/
        initComponents();
      populateJTable();
      
      
            query mq = new query();
        ArrayList<product> list = mq.www();
        String[] columnName = {"التسلسل","المادة","النوع","الكمية"};
        Object[][] rows = new Object[list.size()][6];
        for(int i = 0; i < list.size(); i++){
            
            rows[i][0]=list.get(i).getId();
            rows[i][1]=list.get(i).getName();
            rows[i][2]=list.get(i).getType();
            rows[i][3]=list.get(i).getkmeaa();
          
           
          
           
        }
        
        themodel model = new themodel(rows, columnName);
        jTable1.setModel(model);
        jTable1.setRowHeight(40);
        
   JTableHeader theader = jTable1.getTableHeader();
   theader.setBackground(Color.red);
     theader.setPreferredSize(new Dimension(100, headeer));
     
       theader.setForeground(Color.black);
       
          Font f = new Font("Arial", Font.BOLD, 20);
           theader.setFont(f);
            ((DefaultTableCellRenderer)theader.getDefaultRenderer())
             .setHorizontalAlignment(JLabel.CENTER);
         /*.....>.......................................................................*/
             DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
          rightRenderer.setHorizontalAlignment((int) CENTER_ALIGNMENT);
       TableModel tableModel = jTable1.getModel();
      for (int columnIndex = 0; columnIndex < tableModel.getColumnCount(); columnIndex++)
   {
    jTable1.getColumnModel().getColumn(columnIndex).setCellRenderer(rightRenderer);
 }
      
      
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton11 = new javax.swing.JButton();

        setBackground(new java.awt.Color(44, 62, 80));
        setPreferredSize(new java.awt.Dimension(800, 636));

        jTable1.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jTable1.setRowMargin(8);
        jScrollPane1.setViewportView(jTable1);

        jButton11.setBackground(new java.awt.Color(255, 0, 0));
        jButton11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Delete-icon.png"))); // NOI18N
        jButton11.setText("حذف مخزون");
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton11)
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 213, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        try{
            con=Connections.getConnection();

            int aa=jTable1.getSelectedRow();
            String aaa=(jTable1.getModel().getValueAt(aa,0).toString());
            String sql="DELETE  FROM makhzn WHERE itemid="+aaa;
            PreparedStatement pst=con.prepareStatement(sql);

            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "تم الحذف");
            populateJTable();
        }
        catch(Exception e){
            System.out.print(e);

        }
    }//GEN-LAST:event_jButton11ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton11;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
public void populateJTable(){
  
        
        
        query mq = new query();
        ArrayList<product> list = mq.www();
        String[] columnName = {"التسلسل","المادة","النوع","الكمية"};
        Object[][] rows = new Object[list.size()][6];
        for(int i = 0; i < list.size(); i++){
            
            rows[i][0]=list.get(i).getId();
            rows[i][1]=list.get(i).getName();
            rows[i][2]=list.get(i).getType();
            rows[i][3]=list.get(i).getkmeaa();
          
           
          
           
        }
        
        themodel model = new themodel(rows, columnName);
        jTable1.setModel(model);
        jTable1.setRowHeight(40);
        
   JTableHeader theader = jTable1.getTableHeader();
   theader.setBackground(Color.red);
     theader.setPreferredSize(new Dimension(100, headeer));
     
       theader.setForeground(Color.black);
       
          Font f = new Font("Arial", Font.BOLD, 20);
           theader.setFont(f);
            ((DefaultTableCellRenderer)theader.getDefaultRenderer())
             .setHorizontalAlignment(JLabel.CENTER);
         /*.....>.......................................................................*/
             DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
          rightRenderer.setHorizontalAlignment((int) CENTER_ALIGNMENT);
       TableModel tableModel = jTable1.getModel();
      for (int columnIndex = 0; columnIndex < tableModel.getColumnCount(); columnIndex++)
   {
    jTable1.getColumnModel().getColumn(columnIndex).setCellRenderer(rightRenderer);
 }
      
        
        
        
        
    }
        
   } 
  
    
    






